### ISSUE TITLE
Use new Source interface defined in FLIP-27

### ISSUE THREAD

**Issue by dnault** [couchbaselabs/flink-connector-couchbase#2]
FLIP-27: Refactor Source Interface
https://cwiki.apache.org/confluence/display/FLINK/FLIP-27%3A+Refactor+Source+Interface

Scheduled for inclusion in Flink 1.11 -- will hopefully simplify how the connector manages partitions and state.

**Comment by chedim** [comment]
see #6

**Comment by chedim** [comment]
Released 0.4.0-SNAPSHOT with updated APIs. Please consult with readme on how to get the artifact from maven snapshots repo. 
Thank you!
