### ISSUE TITLE
Investigate batch writing

### ISSUE THREAD

**Issue by dnault** [couchbaselabs/flink-connector-couchbase#3]
The Couchbase sink is currently processes one document at a time. Can we run some kind of transformation on the stream and collect the documents into batches and write one batch at a time, so that all documents within the batch can be upserted asynchronously?

**Comment by dnault** [comment]
Specifically, a tumbling window with "count" trigger.

**Comment by dnault** [comment]
https://flink.apache.org/2022/03/16/the-generic-asynchronous-base-sink/

**Comment by chedim** [comment]
#6 adds new sink that supports batch writing.

**Comment by chedim** [comment]
Released 0.4.0-SNAPSHOT. Please consult with readme on how to get the artifact from maven snapshots repo. 
Thank you!
