### ISSUE TITLE
[Enhancement] Support Couchbase Collections

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/flink-connector-couchbase#4]
Request is to add support for scopes and collections with the sink and source connector portion of this connector.
currently only defaultCollections() is supported.

**Comment by chedim** [comment]
see #6

**Comment by chedim** [comment]
Released 0.4.0-SNAPSHOT with a new set of source and sink classes that support collections. Please consult with readme on how to get the artifact from maven snapshots repo. 
Thank you!
