### ISSUE TITLE
Bump dependencies Couchbase/Flink

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/flink-connector-couchbase#5]
Currently Couchbase Java SDK is 3.0.5 and DCP is 0.28, we need to bump dependencies.
Current version is 3.4.6 and DCP version is 0.48
Additionally flink version is also not up to date.

**Comment by chedim** [comment]
see #6

**Comment by chedim** [comment]
Released 0.4.0-SNAPSHOT with updated dependencies. Please consult with readme on how to get the artifact from maven snapshots repo. 
Thank you!
